name: CI/CD Pipeline

on:
  schedule:
    - cron: '0 */6 * * *'  # Runs every 6 hours (UTC)
  workflow_dispatch:        # Allows manual trigger from GitHub
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  run-main:
    runs-on: ubuntu-latest
    timeout-minutes: 360  # Optional: sets max job time to 6 hours

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Set up Python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r ai_agent/requirements.txt
          python -m spacy download en_core_web_sm

      - name: Run blog_generator_new.py
        run: python ai_agent/blog_generator_new.py
